/**
 * TODO
 */

export enum TransactionStatus {
  SUBMITTED = 'SUBMITTED',
  REPRICED = 'REPRICED',
  CANCELLED = 'CANCELLED',
  MINED = 'MINED',
  UNCHECKED = 'UNCHECKED',
  PROCESSING = 'PROCESSING',
  OK = 'OK',
  INDETERMINATE = 'INDETERMINATE',
  ERROR = 'ERROR',
  INVALID_PARAMS = 'INVALID_PARAMS',
  INVALID_REQUEST = 'INVALID_REQUEST'
}
